# 
# Makefile.tmpl for the mod_fastcgi module
#
#   Apache v1.3's Configure uses this to create a Makefile 
# 
# $Id: Makefile.tmpl,v 1.3 1999/02/09 03:07:57 roberts Exp $

LIB=libfastcgi.$(LIBEXT)

OBJS=mod_fastcgi.o fcgi_buf.o fcgi_pm.o fcgi_protocol.o	fcgi_config.o fcgi_util.o

# Build commands

all:  lib
lib: $(LIB)

$(LIB): $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	$(RANLIB) $@
 
.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $<

clean:
	rm -f $(LIB) $(OBJS)

distclean: clean
	rm -f Makefile


# NOT FOR END USERS!
depend:
	cp Makefile.tmpl Makefile.tmpl.bak \
	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && gcc -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' \
	           -e '1,$$s: $(OSDIR)/: $$(OSDIR)/:g' Makefile.new \
		> Makefile.tmpl \
	    && rm Makefile.new

# Dependencies

$(OBJS): fcgi.h
fcgi.h: mod_fastcgi.h fcgi_protocol.h
fcgi_protocol.o: fcgi_protocol.h
mod_fastcgi.o:   $(INCDIR)/httpd.h                \
                 $(INCDIR)/http_config.h          \
		 $(INCDIR)/http_request.h         \
                 $(INCDIR)/http_core.h            \
                 $(INCDIR)/http_protocol.h        \
                 $(INCDIR)/http_main.h 	          \
                 $(INCDIR)/http_log.h  	          \
                 $(INCDIR)/util_script.h          \
                 $(INCDIR)/http_conf_globals.h    \
                 $(INCDIR)/util_md5.h  
